AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  SimpleEventLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SimpleEventLambda
      CodeUri: lambda.js.zip
      Handler: lambda.simpleEventHandler
      Runtime: nodejs12.x

Outputs:
  SimpleEventLambdaArn:
    Value: !GetAtt SimpleEventLambda.Arn