AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  TestQueueArn:
    Description: arn of the queue
    Type: String

Resources:
  SimpleEventLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SimpleEventLambda
      CodeUri: lambda.js.zip
      Handler: lambda.simpleEventHandler
      Runtime: nodejs18.x

  SqsEventLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SqsEventLambda
      CodeUri: lambda.js.zip
      Handler: lambda.sqsEventHandler
      Runtime: nodejs18.x
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          FORWARD_QUEUE: myForwardQueue
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !Ref TestQueueArn
            BatchSize: 10

Outputs:
  SimpleEventLambdaArn:
    Value: !GetAtt SimpleEventLambda.Arn
  SqsEventLambdaArn:
    Value: !GetAtt SqsEventLambda.Arn
