AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  RuntimeTestQueue:
    Description: name of the test queue
    Type: String
    Default: myQueue
  RuntimeForwardQueue:
    Description: name of the forward queue
    Type: String
    Default: myForwardQueue

Resources:
  TestQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: queue.yml
      Parameters:
        RuntimeQueue: !Ref RuntimeTestQueue

  ForwardQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: queue.yml
      Parameters:
        RuntimeQueue: !Ref RuntimeForwardQueue

# Nestesd template for Lambdas doesn't work with localstack 2.0.0+
# It fails with a CAPABILITY_AUTO_EXPAND error
# Including lambdas directly instead
#
#  Lambdas:
#    Type: AWS::CloudFormation::Stack
#    Properties:
#      TemplateURL: lambda.yml
#      Parameters:
#        TestQueueArn: !GetAtt TestQueue.Outputs.QueueArn

  SimpleEventLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SimpleEventLambda
      CodeUri: lambda.js.zip
      Handler: lambda.simpleEventHandler
      Runtime: nodejs18.x

  SqsEventLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SqsEventLambda
      CodeUri: lambda.js.zip
      Handler: lambda.sqsEventHandler
      Runtime: nodejs18.x
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          FORWARD_QUEUE: myForwardQueue
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt TestQueue.Outputs.QueueArn
            BatchSize: 10


  Dynamo:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: dynamo-tables.yml