version: '3.7'

services:
  localstack:
    image: localstack/localstack:0.12.17
    container_name: localstack
    ports:
      - 4566:4566
    network_mode: bridge
    volumes:
      - ../dist/:/opt/dist
      - /tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SERVICE: cloudformation,s3,sqs,lambda
      DEBUG: 1
      DEFAULT_REGION: us-east-1
      HOSTNAME_EXTERNAL: 172.17.0.2
      LAMBDA_EXECUTOR: docker
      LAMBDA_REMOTE_DOCKER: 'false'
      DATA_DIR: /tmp/localstack/data
      DOCKER_HOST: unix:///var/run/docker.sock
