version: '3.7'

services:
  localstack:
    image: localstack/localstack:3.4.0
    container_name: localstack
    ports:
      - 4566:4566
    network_mode: bridge
    volumes:
      - ../dist/:/opt/dist
      - ./volume:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SERVICE: cloudformation,s3,sqs,lambda,dynamodb
      DEBUG: 1
      DOCKER_HOST: unix:///var/run/docker.sock
